name: Terraform CI/CD pipeline

on: 
  push: 
    branches:
      - main
  pull_request:
    branches: 
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with: 
          terraform_version: "1.8.2"

      - name: Terraform init
        run: terraform init
        
      - name: Terraform plan
        run: terraform plan

      - name: Terraform apply
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'   
